baseURL = "https://husio.github.io/blog"
languageCode = "en-us"
title = "Blog"
theme = "justtext"
publishDir = "docs"
pygmentsCodeFences = true
pygmentsStyle = "borland"

[author]
name = "Piotr Husiaty≈Ñski"
homepage = "https://husio.github.io/"

[params]
githubUsername = "husio"
twitterUsername = "PiotrHusiatyski"
cvLink = "https://stackoverflow.com/cv/piotrhusiatynski"
licenseTag = 'The content of this page is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'
